### ISSUE TITLE
request to change your tutorial

### ISSUE THREAD

**Issue by DennisHeimbigner** [USEPA/CMAQ#121]
In order to keep current with respect to netcdf-c and netcdf-fortran
installation, I would suggest you modify your tutorial page
(https://github.com/USEPA/CMAQ/blob/5.2.1/DOCS/Tutorials/CMAQ_GettingStarted.md)
to refer to the following pages at unidata:
1. Install netcdf-c : https://www.unidata.ucar.edu/software/netcdf/docs/getting_and_building_netcdf.html
2. Install netcdf-fortran : https://www.unidata.ucar.edu/software/netcdf/docs/building_netcdf_fortran.html

**Comment by lizadams** [comment]
Thank you! For the upcoming release we have updated our instructions.
