### ISSUE TITLE
How to modify the dry deposition velocity for a specific area?

### ISSUE THREAD

**Issue by lovechang1986** [USEPA/CMAQ#124]
I need to modify the dry deposition velocity for a specific area.
 
So I change the file: /project/yoj/arc/CCTM/src/aero/aero5/aero_depv.F
After the line 277:
IF (C .GT. 10 .AND. C .LT. 20 .AND R .GT. 10 .AND. R .LT. 20) THEN
    VDEP_AE(V, C, R) = 100.0
ENDIF

But there were no difference between modified dry deposition velocity and unmodify, only some noisy.

Can someone help solve this problem?

**Comment by lovechang1986** [comment]
I found that this is due to the multi-core operation, the original grid is divided into blocks, the index in each block is inconsistent with the index of the original array.  
Of course, there is no problem with the single core runtime, but this is too slow. 

How can I solve this?

**Comment by kmfoley** [comment]
Thank you for your question and your interest in the CMAQ system.  We ask that you please post your question to the CMAS Center Forum:  https://forum.cmascenter.org/
