### ISSUE TITLE
ISAM predictions of secondary gas species

### ISSUE THREAD

**Issue by sergeynk** [USEPA/CMAQ#136]
CMAQv5.3.1-i1:
Date: 12/19/2019 Contact: Sergey Napelenok (napelenok.sergey@epa.gov)

Description
CMAQ-ISAM overcontributes apportionment of secondary gaseous pollutants to the ICON and BCON tags. As the result, contributions to other tracked sources is underestimated.

Scope and Impact
All secondary gas-phase species (O3, NOx, etc.) in CMAQ-ISAM v5.3 and v5.3.1.

Solution
A modification to the ISAM chemistry algorithms is currenlty in testing. It will be released in the near future.

**Comment by kmfoley** [comment]
Resolved with release of v5.3.2.
[See v5.3.2 Release Notes](https://github.com/USEPA/CMAQ/blob/master/DOCS/Release_Notes/ISAM_gas_chemistry_v532.md)
