### ISSUE TITLE
Mercator projection not supported in nested simulations

### ISSUE THREAD

**Issue by pgamez** [USEPA/CMAQ#141]
Hi,

[CMAQ docs](https://github.com/USEPA/CMAQ/blob/master/DOCS/Users_Guide/Appendix/CMAQ_UG_appendixC_spatial_data.md#c3-spatial-data-projection) says:

> CMAQ can use any of the four map projections defined for WRF. The four map projection coordinate systems are regular latitude-longitude geographic, Lambert conformal conic, **Mercator**, and Polar stereographic

but I noticed that mercator projection is actually not supported by modules ICON and BCON with  the `m3conc` option. 

In order to implement this projection:

1. IOAPI v3.2 is required (because 3.1 has a bug that affects directly to this matter)
2. Add these lines to files `PREP/bcon/src/common/lat_lon.F` and  `PREP/icon/src/common/lat_lon.F` at line `115`:

```fortran
      ELSE IF ( GDTYP .EQ. EQMGRD3 ) THEN  ! Equatorial Mercator

         IF ( .NOT. SETEQM( SNGL( P_ALP ),        !  first, initialize
     &                      SNGL( P_BET ),        !  for EQM2LL()
     &                      SNGL( P_GAM ),
     &                      SNGL( XCENT ),
     &                      SNGL( YCENT ) ) ) THEN
            MSG = 'Eq Mercator projection setup error for CTM CONC file'
            CALL M3EXIT( PNAME, 0, 0, MSG, 2 )
         END IF

         X = X0 + FLOAT( COL ) * SNGL( XCELL )
         Y = Y0 + FLOAT( ROW ) * SNGL( YCELL )
         IF ( .NOT. EQM2LL( X, Y, LON, LAT ) ) THEN
            MSG = 'Eq Mercator conversion error for CTM CONC file'
            CALL M3EXIT( PNAME, 0, 0, MSG, 2 )
         END IF
```
Thanks

Pedro

**Comment by kmfoley** [comment]
Hi Pedro,
Thank you for alerting us to this issue in the documentation and for sharing a solution for ICON and BCON.  We will update the documentation to reflect that we currently only support three map projections.  Note that in addition to ICON and BCON, there are other PREP and POST tools in the CMAQ repository that also do not currently support Mercator map projections.  We will consider adding support for Mercator in a future release.
