### ISSUE TITLE
Can we make a docker image for CMAQ to simplify the installation process?

### ISSUE THREAD

**Issue by UtkarshChemE** [USEPA/CMAQ#151]
A containers (Docker, Singularity, etc.) with working CMAQ setups will be a really helpful and save a lot of time while deploying this tools.

**Comment by kmfoley** [comment]
Thank you for your comment. We are currently working on a Singularity container for CMAQ.  We agree that this option could greatly simplify the installation process for many users.  After additional testing and documentation we hope to release this with a future release for users to try out and provide feedback.
