### ISSUE TITLE
Instructions to install IO API are incorrect

### ISSUE THREAD

**Issue by mboisson** [USEPA/CMAQ#152]
The instructions for IO API on this page
https://github.com/USEPA/CMAQ/blob/master/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_build_library_gcc.md
are just plain wrong. 

I don't know what they are supposed to be, but if you 
mkdir $BIN
and then
cd $BIN

you won't have any Makefile in that directory to run "make" on... 

Nor are there any Makefile in the "ioapi" directory either. 

There are *tons* of Makefile... but none called "Makefile", which is the only default target for the "make" command.

**Comment by lizadams** [comment]
My apologies. I will take a look and make corrections.

**Comment by lizadams** [comment]
Please take a look at the modifications that I made to see if you can follow the new instructions. 
Note, if you are using the git clone method, I provided instructions for you to switch to a stable tagged branch.

**Comment by mboisson** [comment]
I ended up using EasyBuild, with this recipe https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/i/ioapi/ioapi-3.2-2020111-GCC-9.3.0.eb

**Comment by farzad685** [comment]
@mboisson.Hi, thanks for suggesting EasyBuild.
I've installed it (EasyBuild-4.3.0) to install I/O API.
but when run this `eb -S ioapi` to search the I/O API library, your suggesting version of I/O API does not exist .(ioapi-3.2-GCC-9.3.0.eb)
just  this version (ioapi-3.2-2020111-gompi-2019b-nocpl.eb) exists .
could you help me?

**Comment by mboisson** [comment]
@farzad685 ah, I did not contribute back the recipe I think. I can probably do that next week, but you might be able to download the recipe I linked and install it still.

**Comment by farzad685** [comment]
@mboisson. I am not very good at programming. How can I install the recipe?
Do you know what gompi stands for?(I think GCC-OPEN MPI, right?)
As you know the instruction of ioapi is so confusing(maybe, it is just for me ).
I've tried many ways to install it but it's too difficult to install ioapi from that instruction. (maybe, I am so bad at doing.)

**Comment by mboisson** [comment]
@farzad685, `gompi` does stand for GCC + OpenMPI, indeed. 

And I see why I did not contribute it back. In the upstream EasyBuild repository, they are/were installing netCDF with MPI, while we install it without MPI.
