### ISSUE TITLE
Night AOD or aerosol extinction is zero from CCTM_PHOTDIAG3 file  simulated by CMAQv5.3.1?

### ISSUE THREAD

**Issue by gc13141112** [USEPA/CMAQ#159]
Daytime
![image](https://user-images.githubusercontent.com/20677298/124056656-b7c43b00-da58-11eb-9377-b598925f9218.png)
Nightime
![image](https://user-images.githubusercontent.com/20677298/124056698-c7438400-da58-11eb-9a79-908d50601b32.png)
 If so, any recommendation how to fix this problem?

**Comment by chogrefe** [comment]
For a given time step, the photolysis module calculating these diagnostic variables is only called when the solar radiation in a given grid cell is greater than zero (i.e. daytime). During nighttime, there is no photolysis and no light extinction by aerosols. The best way to think about these zero nighttime values is "AOD / aerosol extinction not available", analogous to how satellite products also do not provide any AOD during night. While "real" AOD / aerosol extinction values probably never go down to zero even in the cleanest environments, you could filter by solar radiation from METCRO2D (variable RGRND) to set all zero AOD values to missing when RGRND equals zero if this helps with your analysis.

Please also keep in mind that the primary avenue for answering CMAQ-related questions and providing user support is the [CMAQ forum](https://forum.cmascenter.org/).
