### ISSUE TITLE
Error in SpecDef_cb6r3_ae6_aq.txt definition of VOC in CMAQ v5.3.2 op and dev branches

### ISSUE THREAD

**Issue by ushankar-cmd** [USEPA/CMAQ#162]
The formula has a redundant occurrence of the term 
2.0*ETHA[1]. This was confirmed as an error by Christian Hogrefe when checked against the 5.2.1 release code base (https://github.com/USEPA/CMAQ/blob/5.2.1/CCTM/src/MECHS/cb6r3_ae6_aq/SpecDef_cb6r3_ae6_aq.txt). The formula is commented out but could be uncommented and used, and needs to be corrected.

**Comment by kmfoley** [comment]
Thank you for letting us know.  The correction has now been made to the SpecDef_cb6r3_ae6_aq.txt file on the 5.3, 5.3.1, 5.3.2, and main branches.
