### ISSUE TITLE
Benchmark model run gives only WRF output; no ACONC output

### ISSUE THREAD

**Issue by bismarck99** [USEPA/CMAQ#174]
**Description**
WRF-CMAQ functions like WRF model.

**Scope and Impact**
Downloaded the WRF-CMAQ source code and input files for the two-day benchmark case. All the executables were successfully built as described at https://github.com/USEPA/CMAQ/blob/main/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_WRF-CMAQ_build_gcc.md
The model runs but gives only WRF output, regardless of 'wrf_cmaq_option' setting. Is this normal?

**Solution**
Either the runscript or the code itself is missing something??

**Additional context**
Another on CMAQ user forum has reported same issue. Kindly assist.

**Comment by fisidi** [comment]
@bismarck99 what version of WRF and CMAQ are you trying to couple? 

If you are interested you can try the newly released WRFv4.4 with CMAQv5.3.3+. See the updated [WRF-CMAQ tutorial]( https://github.com/USEPA/CMAQ/blob/5.3.3%2B/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_WRF-CMAQ_Benchmark.md). 

If you follow this tutorial and are still having the same issues please let us know.

**Comment by bismarck99** [comment]
I coupled the WRFv4.3-CMAQv5.3.3 , but it produced only wrfout, regardless of the of 'wrf_cmaq_option' setting. For the of WRFv4.4-CMAQv5.3.3+ version you referred me, the build reports errors starting from when -lwrfio_nf links to ndown:

-lnetcdff -lnetcdf           -lhdf5_hl -lhdf5 -lz  
ndown_em.o: In function `vert_cor_':
ndown_em.f90:(.text+0xd93c): undefined reference to `compute_vcoord_1d_coeffs_'
ndown_em.o: In function `MAIN__':
ndown_em.f90:(.text+0x120ba): undefined reference to `init_domain_constants_em_'
Anyway to bypass ndown as I  do not really need the ndown.exe?
....
...

**Comment by fisidi** [comment]
@bismarck99, I'm not sure why ndown.exe compilation broke... but currently you do not need ndown. If you have main/wrf.exe built then you should be fine.

Please check the build log for any other errors... or share your compile log.

**Comment by bismarck99** [comment]
It broke before any executable could be created, so not having main/wrf.exe. Attached below is the compile log
[compile.log](https://github.com/USEPA/CMAQ/files/8683049/compile.log)
.

**Comment by fisidi** [comment]
@bismarck99 thanks for the compile.log. A couple of things I noticed and related questions: 

1. I noticed that the CMAQ program that creates the Makefile for the CMAQ subroutines (bldmake) did not successfully build. You can see verify this by going to the root of your **project directory** and navigating to UTIL/bldmake to see if you see bldmake_*.exe.

2. Did you run bldit_project.csh already setting up a **project directory** which is separate from your repo directory? If not please revisit https://github.com/USEPA/CMAQ/blob/5.3.3%2B/DOCS/Users_Guide/Tutorials/CMAQ_UG_tutorial_WRF-CMAQ_Benchmark.md#building-and-running-in-a-user-specified-directory-outside-of-the-repository. 

Distinguishing your repo from your project directory, is the intended workflow for CMAQ code. 

For example my git clone of CMAQ may sit in /home/fsidi/git_repos/CMAQ (this contains a clean version of the code, free of compiled source code or other modified files). 

While my project directory may sit in /home/fsidi/projects/CMAQ_Twoway (this contains all compiled code and modified files).

**Comment by bismarck99** [comment]
git clone -b v5.3.3+ https://github.com/USEPA/CMAQ.git CMAQ_REPO
It says 
USEPA/CMAQ.git CMAQ_REPO
Cloning into 'CMAQ_REPO'...
fatal: Remote branch v5.3.3+ not found in upstream origin
Unexpected end of command stream

**Comment by fisidi** [comment]
@bismarck99 apologies. That should say:

```
git clone -b 5.3.3+ https://github.com/USEPA/CMAQ.git CMAQ_REPO
```

**Comment by bismarck99** [comment]
Okay, so I 've got separate project and repo directories for the installation and the bldmake_*.exe now exists, but I 've got undefined references that occur before, and in addition to those that were previously reported for the link to -lwrfio_nf 
libwrflib.a(module_dm.o): In function `feedback_domain_em_part2_':
module_dm.f90:(.text+0x1db0cd): undefined reference to `cd_feedback_mask_'
...
..
The log file is attached.
[compile2.log](https://github.com/USEPA/CMAQ/files/8683878/compile2.log)

**Comment by fisidi** [comment]
@bismarck99 thanks for attaching your log file. This log looks much, much **better**! The compile problems I see appear to be coming from the WRF side now (the CMAQ side compiled successfully this time, you can verify by checking BLD_WRFv4.4_CCTM_v533_gcc/main/libcmaq.a). 

The WRF error report is: 

```
rm -f ../phys/module_firebrand_spotting.o
sed -e "s/^\!.*'.*//" -e "s/^ *\!.*'.*//" ../phys/module_firebrand_spotting.F > ../phys/module_firebrand_spotting.G
/lib/cpp -P -nostdinc -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/inc -DEM_CORE=1 -DNMM_CORE=0 -DNMM_MAX_DIM=2600 -DDA_CORE=0 -DWRFPLUS=0 -DIWORDSIZE=4 -DDWORDSIZE=8 -DRWORDSIZE=4 -DLWORDSIZE=4 -DNONSTANDARD_SYSTEM_SUBR  -DWRF_USE_CLM -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT -DNO_IEEE_MODULE  -DDM_PARALLEL -DNETCDF -DLANDREAD_STUB=1 -DUSE_ALLOCATABLES -Dwrfmodel -DGRIB1 -DINTIO -DKEEP_INT_AROUND -DLIMIT_ARGS -DBUILD_RRTMG_FAST=0 -DBUILD_RRTMK=0 -DBUILD_SBM_FAST=1 -DSHOW_ALL_VARS_USED=0 -DCONFIG_BUF_LEN=65536 -DMAX_DOMAINS_F=21 -DMAX_HISTORY=25 -DNMM_NEST=0 -DWRF_CMAQ -I. -traditional-cpp -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT   ../phys/module_firebrand_spotting.G  > ../phys/module_firebrand_spotting.bb
/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/tools/standard.exe ../phys/module_firebrand_spotting.bb | /lib/cpp -P -nostdinc -traditional-cpp -DUSE_NETCDF4_FEATURES -DWRFIO_NCD_LARGE_FILE_SUPPORT > ../phys/module_firebrand_spotting.f90
rm -f ../phys/module_firebrand_spotting.G ../phys/module_firebrand_spotting.bb
time mpif90  -o ../phys/module_firebrand_spotting.o -c -O2 -ftree-vectorize -funroll-loops -w -ffree-form -ffree-line-length-none -fconvert=big-endian -frecord-marker=4    -I../dyn_em -I../cmaq  -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/external/esmf_time_f90  -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/main -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/external/io_netcdf -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/external/io_int -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/frame -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/share -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/phys -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/wrftladj -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/chem -I/data/researchHome/onwukwe/M3_MODELS/MAC2WAY/CCTM/scripts/BLD_WRFv4.4_CCTM_v533_gcc/inc -I/data/researchHome/onwukwe/Toolbox/gnu_nc4/include    ../phys/module_firebrand_spotting.f90
../phys/module_firebrand_spotting.f90:12.21:

    USE, INTRINSIC :: IEEE_ARITHMETIC
                     1
Fatal Error: Can't find an intrinsic module named 'ieee_arithmetic' at (1)

```

This change was made specifically in WRFv4.4 with [PR #1657](https://github.com/wrf-model/WRF/pull/1657). However, in doing this change it broke backward compatibility with older versions of the GFortran compiler. Gfortran did not add this feature until v5.0 series ( see documentation here https://gcc.gnu.org/gcc-5/changes.html). From the log file it looks like the compiler you are using is v4.8.5 which does not have the feature (for peace of mind, I compiled WRFv4.4-CMAQv5.3.3+ on my system with Gfortran version 4.8.5 and it failed with the same exact messages). 

There are a couple of options you may want to explore (some easier than others...): 

1. Upgrade your compiler -- this may not be an easy option because it requires re-building all ancillary libraries (e.g., netCDF-C, netCDF-Fortran, I/O API). 
2. Downgrade your version of WRF-CMAQ to WRFv4.3-CMAQv5.3.3. Here the same exact steps can be followed as with WRFv4.4-CMAQv5.3.3+, except the first step should be: 

```
git clone https://github.com/USEPA/CMAQ.git CMAQ_REPO
```

This step might be easier given that you already went through the WRFv4.4-CMAQv5.3.3+ successfully after splitting your repository and project directory.

**Comment by bismarck99** [comment]
Thanks for the feedback.
Truly, option 1 is n't easy as we do not have a system administrator at the moment, and I am doing all the compilation from my workspace. I would not be able to go with that option.
For option 2, recall that WRFv4.3-CMAQv5.3.3 has been installed previously. I have re-installed it by downloading it with git, and using appropriate NETCDF and IOAPI to create all the *. exe. The PROBLEM I am having, as also stated in my first message is that it is not producing CCTM_ACONC, only wrf output file. Please could you try this out from your end and see if your install of WRFv4.3-CMAQv5.3.3 produces * ACONC for the benchmark 2-day case? I do not understand why it only produces wrfout, even after setting the wrf_cmaq_option to 3.

**Comment by bismarck99** [comment]
Hi, I have used the sample runscript as attached here, and it seems there is a problem with writing the CGRID file:
Runscript Detected an Error: CGRID file was not written. 
How can I resolve this?
[run_cctm_Bench_2016_12SE1.WRFCMAQ.txt
[rsl.error.0000.txt](https://github.com/USEPA/CMAQ/files/8703871/rsl.error.0000.txt)
](https://github.com/USEPA/CMAQ/files/8703849/run_cctm_Bench_2016_12SE1.WRFCMAQ.txt)
[compile.log](https://github.com/USEPA/CMAQ/files/8703855/compile.log)
[job.12371.out.txt](https://github.com/USEPA/CMAQ/files/8703873/job.12371.out.txt)
n

**Comment by fisidi** [comment]
@bismarck99, I'm a bit confused. Your job.12371.out.txt doesn't even show WRF starting?? Yet your rsl.error.0000.txt shows no problems. Another idiosyncrasy I noticed is your rsl.error.0000.txt shows the header as: 

```
 taskid: 0 hostname: compute14.unbc.ca
 module_io_quilt_old.F        2931 F
Quilting with   1 groups of   0 I/O tasks.
 Ntasks in X            6 , ntasks in Y            6
  Domain # 1: dx = 12000.000 m
WRF V4.2.2 MODEL
```

Note the WRF version... it should say 'WRF V4.3 MODEL', so are you sure you shared the correct rsl.error? 

Please also post your rsl.out.000.txt, that one contains much more information that I can look at.

**Comment by bismarck99** [comment]
Hi, Please find attached the rsl.out.0000 file. Certainly, it is weird that the WRF version is indicating WRF 4.2.2 , but that is exactly what it is, being that the model was compiled from the WRF-CMAQ git clone that I was directed to. You will find in the file where it says WRF ran successfully, but certainly, something is odd with not producing ACONC.
[rsl.out.0000.txt](https://github.com/USEPA/CMAQ/files/8704104/rsl.out.0000.txt)

**Comment by fisidi** [comment]
@bismarck99 your compile.log indicates you compiled the right version (WRFv4.3 with CMAQv5.3.3). Your rsl.out.000.txt does not show any CMAQ logging making me think CMAQ is never called. 

Could you try setting:

```
setenv CTM_DIAG_LVL 1
```

In the benchmark runscripts. This option will echo the entire runscript as each command is executed. Then please post the job.*.out.txt.

**Comment by bismarck99** [comment]
Thanks for your assistance so far. It is possible that CMAQ is not called, although not knowing why. I have in this order, the job*. out.txt, job*.err.txt, the runscript, the rsl.error.0000.txt and rsl.out.0000.txt, after setting setenv CTM_DIAG_LVL 1. Perhaps, the issue could be from around line 1005 of the runscript. 
[job.12379.out.txt](https://github.com/USEPA/CMAQ/files/8704771/job.12379.out.txt)
[job.12379.err.txt](https://github.com/USEPA/CMAQ/files/8704774/job.12379.err.txt)
[run_cctm_Bench_2016_12SE1.WRFCMAQ.txt](https://github.com/USEPA/CMAQ/files/8704781/run_cctm_Bench_2016_12SE1.WRFCMAQ.txt)
[rsl.error.0000.txt](https://github.com/USEPA/CMAQ/files/8704776/rsl.error.0000.txt)
[rsl.out.0000.txt](https://github.com/USEPA/CMAQ/files/8704780/rsl.out.0000.txt)

**Comment by fisidi** [comment]
@bismarck99 nothing I see looks out of the ordinary. The job.* is complaining about CGRID, because you chose option 3 where WRF-CMAQ should have written out the CGRID file (at the end of the simulation day), but since it can't find one it reports an error. To be 100% sure, I even took the script you shared and ran it with my executable and found no errors (CMAQ output including CGRID was successfully written out).

A couple of things to check: 

1. If you navigate to BLD_WRFv4.3_CCTM_v533_gcc/module_wrf_top.f90. In this you should see subroutine wrf_init which contains the variables: 

```
   CHARACTER (LEN=*), PARAMETER :: release_version = 'V4.3'
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'git commit eed56d74b865af4ce9f98ea029226acfe52b0569 17 files changed, 804 insertions(+), 14 deletions(-)'

```
The rsl.* files print this information at the top so if you compiled WRFv4.3-CMAQv5.3.3, you should see this exact statement here. 

2. Try manually deleting the out_dat folder before executing the runscript, sometimes old data can be lurking around and symbolic links fail to be deleted.

3. Attach your namelist.input file here. This can be found in the output directory. I just want to double check the runscript is writing out the namelist.input that WRF reads in.

**Comment by bismarck99** [comment]
Yes, I see that what you stated is in BLD_WRFv4.3_CCTM_v533_gcc/main/module_wrf_top.f90, but what the rsl.* file prints at the top is:
taskid: 0 hostname: compute1.unbc.ca
Quilting with   1 groups of   0 I/O tasks.
 Ntasks in X            6 , ntasks in Y            6
  Domain # 1: dx = 12000.000 m
**WRF V4.2.2 MODEL**
So how come WRF V4.2.2, since the WRF_DIR is set to BLD_WRFv4.3_CCTM_v533_gcc ?
I have deleted the out_dat folder and executed the runscript but same issue. 
My namelist.input in the output directory is attached below:
[namelist.input.txt](https://github.com/USEPA/CMAQ/files/8711804/namelist.input.txt)
Perhaps, it would be good if you send me the very WRF-CMAQ code from which you built the model that works at your end.

**Comment by fisidi** [comment]
@bismarck99 I certainly code share my code (I like you used the bldscript to build my two-way model obtained from the main branch of CMAQ). 

I'm not sure what's the best way to share my code with you based on your capabilities. I could share through Github (put the code up in public fork) or email. Just let me know.

Out of curiosity, you could `grep -r "V4.2.2" BLD_WRFv4.3_CCTM_v533_gcc` to see if there are any references of V4.2.2 in that BLD directory. 

Are there other places on your cluster that WRF could be installed? Perhaps doing a `which wrf.exe` to see other places the wrf.exe is in your path. I'm starting to think that the runscript is picking up wrf.exe from somewhere else, not the one that you compiled in BLD_WRFv4.3_CCTM_v533_gcc . If this is correct, you would need to change the line in the runscript that says: 

Line (996): 
```
From : 
   time mpirun -np $NPROCS wrf.exe
To: 
   time mpirun -np $NPROCS $OUTDIR/wrf.exe
```

This will ensure that the wrf.exe being called is specifically the one from the output directory.

**Comment by bismarck99** [comment]
Thank you for directing me to this possibility which is true!
There was a system wide wrf.exe that was been picked up by the runscript. I have also set EXEC and ls -al $WRF_DIR/main/wrf.exe, and the benchmark run outputs the CCTM_ACONC files, etc.

I have additional questions relating to input for my application. The MCIP files in the benchmark are set to 'BUFFERED' presumably to provide them as static files. For my application, it is not necessary to set to time-varying files I guess (since this is the coupled version)?

Further, I 've got emissions file, including one that has been processed as point emissions **across vertical layers** by SMOKE.  I am unsure how to specify this in the runscript, as  it appears the benchmark runscript does not envisage pre-processing of point emissions, rather prefers treating plume rise, etc. inline. Could one specify this as a second emissions file just as is done for rwc in the benchmark case (which is an area source). Would the model recognize the point emissions across layers if done this way? My point emissions are a collection of industrial sources, so not keen about various stack groups and emission stream labels.

**Comment by kmfoley** [comment]
Hi @bismarck99, we are glad to hear that the initial problem is now resolved.  Thank you @fisidi for providing guidance on the debug process. 

@bismarck99 we ask that you please post your new question about emissions input files to the CMAS Center Forum: https://forum.cmascenter.org/

We would like this question to be documented on the forum to help other users that may run into similar issues.

Please start a 'New Topic' with an informative title and choose 'CMAQ' as the category. We will make sure you are connected to the appropriate developer and user base. 

I will close this issue since the original problem is now resolved.
