### ISSUE TITLE
 /usr/bin/time: Command not found in CMAQ v.5.3.3 

### ISSUE THREAD

**Issue by bismarck99** [USEPA/CMAQ#177]
Good day,

I am trying to apply use the standalone CMAQ v. 5.3.3 but need help to resolve the above error that seems like the runscript not starting mpirun (There are no rsl.* files). I have it attached here, together with the job*.err.txt and job*.out.txt files. I think user-specific syntax is needed for mpirun, but unsure how to go about it.
[job.12760.err.txt](https://github.com/USEPA/CMAQ/files/8783072/job.12760.err.txt)
[job.12760.out.txt](https://github.com/USEPA/CMAQ/files/8783073/job.12760.out.txt)
[run_cctm_Bench_2016_12SE1.txt](https://github.com/USEPA/CMAQ/files/8783074/run_cctm_Bench_2016_12SE1.txt)

**Comment by kmfoley** [comment]
@bismarck99 we ask that you please post your question to the CMAS Center Forum: https://forum.cmascenter.org/

We would like this question to be documented on the forum to help other users that may run into similar issues.  We use the forum as a central location to track issues across different software tools supported by the CMAS Center.

Please start a 'New Topic' with an informative title and choose 'CMAQ' as the category.
