### ISSUE TITLE
WRF-CMAQ: Average ELMO Output File Gives Erroneous Results 

### ISSUE THREAD

**Issue by bnmurphy** [USEPA/CMAQ#179]
**Description**
It has been discovered that the ELMO output file gives erroneously low results (about 90% low) for all variables when the WRF-CMAQ model is used. This issue does not impact the standard offline CMAQ model, which applies to the vast majority of use cases.

**Scope and Impact**
If you are using WRF-CMAQ with CMAQv5.4, you should not trust the output data on the ELMO files for now.

**Solution**
The temporary solution is to continue using the output variables from CONC and ACONC if you are running WRF-CMAQ. Please also continue to use the SpecDef files with the combine utility from CMAQv5.3.3.

We will solve the bug in the WRF-CMAQ implementation of ELMO and issue the fix as a Pull Request to this repository.

**Additional context**
Again, this only impacts WRF-CMAQ with CMAQv5.4 for output from the ELMO processing module.

**Comment by bandaoshutiao** [comment]
When is it expected to be repaired?

**Comment by bnmurphy** [comment]
We have a proposed fix that has been tested and is currently under internal review. If you have a specific immediate need, let us know and we can send you the updates for your individual use.

**Comment by bandaoshutiao** [comment]
My email is  xiaoszx1999@163.com.

I am very willing to help you test together

**Comment by bnmurphy** [comment]
Thanks for your offer! Please see Pull Request #181

**Comment by kmfoley** [comment]
This issue has been resolved in PR #181 which was merged into the CMAQv5.4+ branch.  The fix will also be included in the next CMAQ release.
