### ISSUE TITLE
MEGAN preprocessor

### ISSUE THREAD

**Issue by ramespada** [USEPA/CMAQ#187]
HI,

In the Documentation (Chapter 4) when describing MEGAN input files, it mentioned a "MEGAN preprocessor", could you share where to find it?

Thanks

**Comment by jeff-willison** [comment]
The preprocessor can be downloaded from this page:

https://bai.ess.uci.edu/megan/data-and-code/megan32

The developers are still working on the documentation for it and it can be somewhat difficult to use. If you have trouble you can email me at willison.jeff@epa.gov and I can help create inputs for you.

**Comment by ramespada** [comment]
Perfect, thanks you for your quick response.

Just a coment, this preprocessor (as far as i can see in the code) doesn't use IOAPI, they just print the values of the input files like this:
```
prepmegan4cmaq_grwform.f90:      write(99,'(a)')"gridID,TreeFrac,CropFrac,ShrubFrac,HerbFrac"
```
And the CMAQ documentation says that the input file is an I/O API GRDDED3 file.

Thanks again for your time

**Comment by jeff-willison** [comment]
That's correct. The "calculator and mechanism mapper code" has a program called TXT2IOAPI that converts the csv files to IOAPI. The "Emission Factor Processor" tool also takes the growthform and ecotype files from the preprocessor and TXT2IOAPI converts that EFP file to IOAPI. The EFP tool requires setting up a python 3 environment.

In summary it's 

preprocessor -> cantype, optional LAI, and optional soil csv files -> TXT2IOAPI
preprocessor -> growthform and ecotype csv files -> EFP -> TXT2IOAPI

They used to have a user guide on their site but I don't see it anymore. Hopefully they post a new one soon. Until then I'm happy to help with creating input files.

**Comment by ramespada** [comment]
Aah, now it makes sense, many thanks Jeff!
