### ISSUE TITLE
Minor Typo in config_cmaq.csh

### ISSUE THREAD

**Issue by HathewayWill** [USEPA/CMAQ#199]
**Description**
There appears to be a minor typo in the config_cmaq.csh file at line 151

**Scope and Impact**
Minor typo can cause issues with sed statement to fine and change the issue

**Solution**
At line 151 change this:
        setenv IOAPI_INCL_DIR   iopai_inc_gcc             #> I/O API include header files

to this:

        setenv IOAPI_INCL_DIR   ioapi_inc_gcc             #> I/O API include header files

**Additional context**

**Comment by kmfoley** [comment]
Thank you, @HathewayWill, for alerting us to this typo.  We have updated the main branch and will get this fix into our 5.4+ branch as well as our internal research branch.  Thank you for your contribution!
