### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by DifficultA** [USEPA/CMAQ#207]
There is support in WRF for compiling on aarch64 with gfortran and gcc (see [here](https://github.com/wrf-model/WRF/blob/fb60d61cc44e2a2e8b8311f0b79185724010d510/arch/configure.defaults#L47))

Are we also able to compile CMAQ on aarch64 with gfortran and gcc?

**Comment by fisidi** [comment]
Thank you for your question and your interest in the CMAQ system. CMAQ should be able to be compiled on aarch64, however, no testing has been done by EPA on that type of architecture to confirm. At this time we are going to close this issue. 

However, may we also ask that you please post additional questions and issues about CMAQ on our Users' Forum: https://forum.cmascenter.org/. We would like this question to be documented on the forum to help other users that may run into similar issues. Please start a 'New Topic' with an informative title and choose 'CMAQ' as the category. This will ensure you are connected to the appropriate developer and user base.
