### ISSUE TITLE
Calculation of PMF_OC in ELMO

### ISSUE THREAD

**Issue by cgnolte** [USEPA/CMAQ#213]
**Description**
There is a bug in the calculation of the ELMO variable PMF_OC (organic carbon in the Aitken and accumulation modes) causing non-carbon organic mass to be included. 

**Solution**
Modify lines 2590-2599 of ELMO_PROC.F as follows:

         CASE ( ID_PMF_OC )
            ! Sum up primary organic aerosol species normalized to
            ! just carbon mass
            VAL = 0.0
            DO IOA = 1,N_OA_NotTracers
               IF ( OASPC( IOA )%OMtoOC .GT. 0.0 ) THEN
                  VAL = VAL + SUM( AEROSPC_CONC( MAP_OAtoAERO(IOA),: ),
     &                        MASK = AEROMODE(:)%FINE_MASK ) 
     &                      / OASPC( IOA )%OMtoOC
               END IF
            END DO
            OUTVAL = VAL

**Comment by kmfoley** [comment]
Resolved with https://github.com/USEPA/CMAQ/pull/215 (merged 2024-04-09).
