### ISSUE TITLE
bldit_project.csh Updates

### ISSUE THREAD

**Issue by zacadelman** [USEPA/CMAQ#45]
Resolve location of a couple of PREP directories in this script:

Fix the ICON, BCON CMAQ_REPO locations.   The directories CMAQ_REPO/PREP/ic/ICON and CMAQ_REPO/PREP/bc/BCON do not exist.

Replace: CMAQ_REPO/PREP/ic/ICON with CMAQ_REPO/PREP/icon
Replace: CMAQ_REPO/PREP/ic/BCON with CMAQ_REPO/PREP/bcon

Remove this whole section: #> Copy LTNG scripts as there are no longer lightning processing scripts needed in the CMAQ package. Regridding of these files is done outside of CMAQ.

**Comment by bnmurphy** [comment]
These actions were taken and the revised code is awaiting internal approval.
