### ISSUE TITLE
Two-Way Model Download

### ISSUE THREAD

**Issue by zacadelman** [USEPA/CMAQ#77]
The instructions for the WRF-CMAQ model on the release notes page are not correct: 

https://github.com/USEPA/CMAQ/blob/5.2/CCTM/docs/Release_Notes/Two_Way_Coupled_WRF-CMAQ.md

```
Download coupled model tarball from the CMAS Center Software Clearinghouse. From http://www.cmascenter.org, select Download -> Software -> CMAQ and choose version 5.2 to download the file WRFv3.8_CMAQv5.2_TwoWay_Model.tar.gz. Unzip the tarball and then move the twoway directory inside WRFV38 as well.
```

There is no tar.gz file on the CMAS page.  Further, we should put the contents of this file up on GitHub so that it downloads with the repo.

**Comment by zacadelman** [comment]
Added a link to the two way package on CMAS, but we should still add these codes to the repo to be part of the download package.

**Comment by mreihani** [comment]
Hello guys,
I have encountered an error during installation of the WRF-CMAQ Coupled Model on my Linux system. Could you please take a look at my log (attached below) as long as I could not find any solution for the error. **(The error begins with: None of WRF_EM_CORE, WRF_NMM_CORE, specified in shell environment....)**
Thanks for your support!
[log-5.txt](https://github.com/USEPA/CMAQ/files/2238624/log-5.txt)

**Comment by kmfoley** [comment]
Please post questions to the CMAS User Forum:  https://forum.cmascenter.org/

Questions about the coupled WRF-CMAQ model can also be sent directly to Wong.David-C@epa.gov
