### ISSUE TITLE
Excessive/Redundant Logging from the CCTM

### ISSUE THREAD

**Issue by zacadelman** [USEPA/CMAQ#82]
When CMAQ is run in MPI mode, the standard output and error receive logging from all processors simultaneously.  While the CTM_LOG files give logging information from each processor individually, the standard output/error gets a jumbled dump of information that is difficult to decipher when there are more than a couple of processors being used. Runs with a large number of processors produce very large and somewhat unreadable logs.  Suggested fix is to either add a flag to disable logging to the standard error/output or to somehow limit to this output to only a single processor, like maybe the master node.

The CTM also outputs a lot of redundant logging information between the CTM_LOG files and the standard output.  I also wonder how much the run times could be improved by giving the option to either disable or limit the information written to the logs.

**Comment by bnmurphy** [comment]
This error has been addressed in a Pull Request currently undergoing internal review at EPA. It is anticipated for release with CMAQv5.3
