### ISSUE TITLE
Inconsistent IOAPI module directory requirement vs error message in config_cmaq.csh

### ISSUE THREAD

**Issue by prehensilecode** [USEPA/CMAQ#95]
The check for m3utilio.mod Fortran module file is:

```
 if ( ! -e $IOAPI_DIR/modules/m3utilio.mod ) then 
    echo "ERROR: $IOAPI_DIR/include/m3utilio.mod does not exist in your CMAQ_LIB directory!!! Check your installation before proceeding with CMAQ build."
    exit
 endif
```

The "if" statement checks for $IOAPI_DIR/modules/m3utilio.mod while the error message mentions $IOAPI_DIR/include/m3utilio.mod

And earlier in the file:

```
 if ( ! -d $IOAPI_DIR ) then 
    mkdir $IOAPI_DIR
    ln -s $IOAPI_MOD_DIR  $IOAPI_DIR/modules
    ln -s $IOAPI_INCL_DIR $IOAPI_DIR/include_files
    ln -s $IOAPI_LIB_DIR  $IOAPI_DIR/lib
 endif
```

it sets the IOAPI_INCL_DIR to yet a different path: $IOAPI_DIR/include_files

**Comment by kmfoley** [comment]
Thank you for identifying this typo.  The fix has been included in CMAQv5.2.1.
